// Imports das imagens dos serviços de moto
import polimentoCarenagemMoto from "@assets/polimentocarenagemmoto_1758084137803.jpg";
import lavaMotorMoto from "@assets/lavamotormoto_1758084137802.jpg";
import enceramentoMoto from "@assets/enceramentomoto_1758084137803.jpg";
import lavagemSimplesMoto from "@assets/lavagem de moto_1758088275200.jpeg";
import lavagemDetalhadaMoto from "@assets/18_1758088287690.jpeg";

export interface Service {
  id: string;
  name: string;
  description: string;
  price: string;
  duration: number;
  image: string;
  vehicleType: 'car' | 'moto' | 'both';
}

export type VehicleType = 'car' | 'moto';

export const services: Service[] = [
  // Serviços para carros
  {
    id: 'vitrificacao-3-anos-hatch',
    name: 'Vitrificação 3 Anos (Hatch)',
    description: 'Proteção premium com durabilidade de 3 anos',
    price: 'R$ 1.200',
    duration: 6,
    image: 'https://images.unsplash.com/photo-1619431856706-ca2cc58258f6?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'vitrificacao-3-anos-sedan',
    name: 'Vitrificação 3 Anos (Sedan)',
    description: 'Proteção premium com durabilidade de 3 anos',
    price: 'R$ 1.500',
    duration: 6,
    image: 'https://images.unsplash.com/photo-1619431856706-ca2cc58258f6?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'vitrificacao-3-anos-pickup',
    name: 'Vitrificação 3 Anos (Pick-up)',
    description: 'Proteção premium com durabilidade de 3 anos',
    price: 'R$ 1.800',
    duration: 6,
    image: 'https://images.unsplash.com/photo-1619431856706-ca2cc58258f6?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'lavagem-simples-carro',
    name: 'Lavagem Simples',
    description: 'Limpeza externa básica com secagem completa',
    price: 'R$ 70',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'lavagem-tecnica',
    name: 'Lavagem Técnica',
    description: 'Limpeza detalhada com produtos específicos',
    price: 'R$ 150',
    duration: 2,
    image: 'https://images.unsplash.com/photo-1708805282706-f44730b7e527?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'higienizacao-completa',
    name: 'Higienização Completa',
    description: 'Limpeza e sanitização interna completa',
    price: 'A partir de R$ 350',
    duration: 3,
    image: 'https://images.unsplash.com/photo-1605437241278-c1806d14a4d9?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'polimento-tecnico',
    name: 'Polimento Técnico',
    description: 'Polimento e correção de pintura com proteção',
    price: 'A partir de R$ 300',
    duration: 3,
    image: 'https://images.unsplash.com/photo-1632823470270-a7d3d03c3e20?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'descontaminacao-pintura',
    name: 'Descontaminação de Pintura',
    description: 'Remoção de impurezas e resíduos da pintura',
    price: 'A partir de R$ 250',
    duration: 2,
    image: 'https://images.unsplash.com/photo-1708805282676-0c15476eb8a2?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'revitalizador-plasticos-externos',
    name: 'Revitalizador de Plásticos Externos',
    description: 'Restauração e proteção dos plásticos externos',
    price: 'R$ 120',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'revitalizador-plasticos-internos',
    name: 'Revitalizador de Plásticos Internos',
    description: 'Restauração e proteção dos plásticos internos',
    price: 'R$ 100',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1620584899131-a5ff5f8fbb03?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'impermeabilizador-vidros',
    name: 'Impermeabilizador de Vidros / Parabrisa',
    description: 'Proteção hidrofóbica que repele água e sujeira',
    price: 'A partir de R$ 150',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1618329397023-cc688d12bb79?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'selante-pneus',
    name: 'Selante nos Pneus',
    description: 'Aplicação de selante com brilho e proteção duradoura',
    price: 'A partir de R$ 30',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1708805282683-50a060eba80f?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'troca-filtro-ar-condicionado',
    name: 'Troca de Filtro de Ar Condicionado',
    description: 'Substituição do filtro e higienização do ar interno',
    price: 'A partir de R$ 60',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1632823470270-a7d3d03c3e20?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'detalhamento-combo',
    name: 'Serviço de Detalhamento (Combo Proteção)',
    description: 'Pacote completo de limpeza, polimento e vitrificação',
    price: 'R$ 950',
    duration: 4,
    image: 'https://images.unsplash.com/photo-1620584898989-d39f7f9ed1b7?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'auto-eletrica',
    name: 'Auto Elétrica',
    description: 'Diagnóstico e reparos elétricos automotivos',
    price: 'Sob orçamento',
    duration: 2,
    image: 'https://images.unsplash.com/photo-1592318348310-f31b61a931c8?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'som-automotivo',
    name: 'Som Automotivo',
    description: 'Instalação e ajustes de som automotivo',
    price: 'Sob orçamento',
    duration: 3,
    image: 'https://images.unsplash.com/photo-1592570714618-15e2d4719c6c?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'insulfilm-profissional',
    name: 'Insulfilm Profissional',
    description: 'Aplicação de película com isolamento térmico',
    price: 'Sob orçamento',
    duration: 1.5,
    image: 'https://images.unsplash.com/photo-1643441431346-37cfc762b4c9?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'pacotes-promocoes',
    name: 'Pacotes e Promoções Especiais',
    description: 'Combos personalizados e descontos',
    price: 'Sob orçamento',
    duration: 4,
    image: 'https://images.unsplash.com/photo-1565689876697-e467b6c54da2?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  {
    id: 'troca-filtro-ar',
    name: 'Troca de Filtro de Ar (Adicional)',
    description: 'Substituição simples do filtro de ar do motor',
    price: 'Sob orçamento',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1592318348310-f31b61a931c8?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'car',
  },
  // Serviços específicos para motos
  {
    id: 'lavagem-simples-moto',
    name: 'Lavagem Simples',
    description: 'Limpeza externa básica e secagem completa',
    price: 'R$ 40',
    duration: 0.75,
    image: lavagemSimplesMoto,
    vehicleType: 'moto',
  },
  {
    id: 'lavagem-detalhada-moto',
    name: 'Lavagem Detalhada',
    description: 'Limpeza completa e minuciosa, incluindo rodas, escapamento e partes cromadas',
    price: 'R$ 60',
    duration: 1.25,
    image: lavagemDetalhadaMoto,
    vehicleType: 'moto',
  },
  {
    id: 'revitalizador-plasticos-externos-moto',
    name: 'Revitalizador de Plásticos Externos',
    description: 'Restauração de plásticos externos com acabamento e proteção UV',
    price: 'R$ 80',
    duration: 1,
    image: 'https://images.unsplash.com/photo-1615906655593-ad0386982a0f?ixlib=rb-4.1.0&auto=format&fit=crop&w=400&h=250',
    vehicleType: 'moto',
  },
  {
    id: 'polimento-carenagem',
    name: 'Polimento de Carenagem',
    description: 'Polimento e proteção das carenagens, tanque e partes pintadas',
    price: 'R$ 120',
    duration: 1.5,
    image: polimentoCarenagemMoto,
    vehicleType: 'moto',
  },
  {
    id: 'limpeza-motor-moto',
    name: 'Limpeza de Motor Moto',
    description: 'Limpeza técnica do motor com produtos específicos e isolamento elétrico',
    price: 'R$ 80',
    duration: 1,
    image: lavaMotorMoto,
    vehicleType: 'moto',
  },
  {
    id: 'enceramento-moto',
    name: 'Enceramento Premium Moto',
    description: 'Enceramento e proteção completa da pintura e cromados',
    price: 'R$ 100',
    duration: 1.25,
    image: enceramentoMoto,
    vehicleType: 'moto',
  },
];
